#!/bin/sh
CONF_TEMPLATE=${CONF_TEMPLATE:-"/usr/local/default.template"}

export SERVER_NAME=${SERVER_NAME:-"localhost"}
export SERVER_ROOT=${SERVER_ROOT:-"/usr/local/nginx/html"}
export LISTEN_PORT=${LISTEN_PORT:-"80"}
echo "Creating configuration from ${CONF_TEMPLATE}"
envsubst < ${CONF_TEMPLATE} > /etc/nginx/conf.d/default.conf

echo "Starting..."
exec "$@"
